#!/usr/bin/env python3
"""Regenerates en.lproj/fr.lproj from design/fr-strings.json.

English is the source language: every Text("...") in the Swift code IS the
English string and doubles as its own key. This file only writes the tables.
The four onboarding.* keys are the exception — that mockup has to run
foreign -> yours in both builds, so its quotes swap sides.
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
FR = json.loads((ROOT / "design/fr-strings.json").read_text())
EN_OVERRIDE = {
    "onboarding.source.lang": "FR",
    "onboarding.source.quote": "«Le crédit privé montre ses premières fissures : Blue Owl à −40 %.»",
    "onboarding.recap.lang": "EN",
    "onboarding.recap.quote": "Private credit is showing its first cracks: Blue Owl down 40%.",
}
esc = lambda x: x.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
head = "/* Generated by design/make-strings.py. Never hand-edit. */\n\n"
fr = head + "".join(f'"{esc(k)}" = "{esc(v)}";\n' for k, v in sorted(FR.items()))
en = head + "".join(f'"{esc(k)}" = "{esc(EN_OVERRIDE.get(k, k))}";\n' for k in sorted(FR))
for base in ("Podcapp/Resources", "ShareExtension"):
    (ROOT / base / "fr.lproj/Localizable.strings").write_text(fr, encoding="utf-8")
    (ROOT / base / "en.lproj/Localizable.strings").write_text(en, encoding="utf-8")
print(f"{len(FR)} strings -> en.lproj + fr.lproj")
