// Renders the privacy policy and the terms into the static site.
//
// Both documents are generated by the API from src/legal/, and that stays the
// single source: this script only writes what those functions already produce
// so podcapp.fr can serve them under its own domain. A legal page whose URL
// says "vercel.app" tells a reader the document belongs to a hosting provider
// rather than to the product, and App Store Connect publishes that URL on the
// listing.
//
// The API keeps serving /privacy and /terms as well. The app links here, but a
// build pointed at a different server can still read that server's documents,
// and Beta App Review's existing link does not break.
//
//   pnpm site:legal
//
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { privacyHtml } from '../src/legal/privacy.js'
import { termsHtml } from '../src/legal/terms.js'

const SITE = new URL('.', import.meta.url).pathname

// The site serves English at the root and French under /fr/, with
// `cleanUrls` + `trailingSlash`, so each page is a directory index.
const PAGES = [
  { path: 'privacy/index.html', html: privacyHtml('en'), french: false },
  { path: 'terms/index.html', html: termsHtml('en'), french: false },
  { path: 'fr/privacy/index.html', html: privacyHtml('fr'), french: true },
  { path: 'fr/terms/index.html', html: termsHtml('fr'), french: true },
]

for (const page of PAGES) {
  // The documents cross-link each other as /privacy and /terms, which is right
  // on the API where one language is served per request but would send a French
  // reader to the English page here, where both live at once.
  const html = page.french
    ? page.html.replaceAll('href="/privacy"', 'href="/fr/privacy/"').replaceAll('href="/terms"', 'href="/fr/terms/"')
    : page.html.replaceAll('href="/privacy"', 'href="/privacy/"').replaceAll('href="/terms"', 'href="/terms/"')

  const out = join(SITE, page.path)
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(out, html)
  console.log(`wrote site/${page.path} (${html.length} bytes)`)
}
