import CoreText
import SwiftUI
import UIKit

// Design tokens decoded from ios/design/layout.html. Every value below appears
// in that markup: screens read from here and never hardcode a color or a size.

// MARK: - Colors

enum Palette {
    // Text
    static let ink = Color(hex: 0x1C1B22)
    static let ink2 = Color(hex: 0x3B3945)
    static let body = Color(hex: 0x4A4854)
    static let muted = Color(hex: 0x6E6C78)
    static let muted2 = Color(hex: 0x77747E)
    static let faint = Color(hex: 0xA5A2AC)
    static let fainter = Color(hex: 0xB0ADB6)
    static let prose = Color(hex: 0x2E2C36)
    static let onDark = Color.white

    // Accents
    static let accentDeep = Color(hex: 0x5B51A8)
    static let accent = Color(hex: 0x7C6CDC)
    static let accentMid = Color(hex: 0x6F68A8)
    static let accentMuted = Color(hex: 0x6F6A96)
    static let accentDark = Color(hex: 0x3F3B58)

    // Status pairs (foreground on background)
    static let success = Color(hex: 0x2E7D46)
    static let successBg = Color(hex: 0x2E7D46, opacity: 0.12)
    static let warning = Color(hex: 0x9A6B00)
    static let warningBg = Color(hex: 0x9A6B00, opacity: 0.12)
    static let danger = Color(hex: 0xB54334)
    static let dangerBg = Color(hex: 0xB54334, opacity: 0.12)
    static let neutralChip = Color(hex: 0x4A4854)
    static let neutralChipBg = Color(hex: 0x1C1B22, opacity: 0.07)
    static let airedChip = Color(hex: 0x77747E)
    static let airedChipBg = Color(hex: 0x1C1B22, opacity: 0.05)

    // Surfaces
    static let cardFill = Color.white.opacity(0.66)
    static let cardBorder = Color(hex: 0x1C1B22, opacity: 0.08)
    static let hairline = Color(hex: 0x1C1B22, opacity: 0.07)
    static let glassBorder = Color(hex: 0x6C5CC8, opacity: 0.28)
    static let glassShadow = Color(hex: 0x3C3278, opacity: 0.16)

    /// Screen background: linear-gradient(180deg, #E9E5F7, #F6F5F1 34%, #FAFAF8).
    static let screenGradient = LinearGradient(
        stops: [
            .init(color: Color(hex: 0xE9E5F7), location: 0),
            .init(color: Color(hex: 0xF6F5F1), location: 0.34),
            .init(color: Color(hex: 0xFAFAF8), location: 1),
        ],
        startPoint: .top,
        endPoint: .bottom
    )

    /// Hero card fill: linear-gradient(140deg, ...). CSS 140deg points down and to
    /// the right, which is why the stops run from upper-left to lower-right here.
    static let glassFill = LinearGradient(
        stops: [
            .init(color: Color(hex: 0x7C6CDC, opacity: 0.30), location: 0),
            .init(color: Color(hex: 0x7C6CDC, opacity: 0.12), location: 0.42),
            .init(color: Color.white.opacity(0.65), location: 1),
        ],
        startPoint: UnitPoint(x: 0.18, y: 0.12),
        endPoint: UnitPoint(x: 0.82, y: 0.88)
    )
}

/// The gradient every screen sits on, edge to edge.
struct ScreenBackground: View {
    var body: some View {
        Palette.screenGradient.ignoresSafeArea()
    }
}

extension Color {
    init(hex: UInt32, opacity: Double = 1) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: opacity
        )
    }
}

// MARK: - Typography

enum Typo {
    /// The three faces bundled in Resources. The file names say Light/Regular/
    /// SemiBold but the PostScript names inside say Light/Medium/Bold, and
    /// PostScript is what Font.custom resolves.
    enum Weight {
        case light, regular, semibold

        var postScriptName: String {
            switch self {
            case .light: return "InterTight-Light"
            case .regular: return "InterTight-Medium"
            case .semibold: return "InterTight-Bold"
            }
        }

        var resourceName: String {
            switch self {
            case .light: return "InterTight-Light"
            case .regular: return "InterTight-Regular"
            case .semibold: return "InterTight-SemiBold"
            }
        }

        var systemFallback: Font.Weight {
            switch self {
            case .light: return .light
            case .regular: return .regular
            case .semibold: return .semibold
            }
        }
    }

    /// The app target's Info.plist is generated by XcodeGen and carries no
    /// UIAppFonts, so the faces are registered at runtime instead. Idempotent:
    /// re-registering an already registered file just fails harmlessly.
    @discardableResult
    static func registerFonts() -> Bool {
        for weight in [Weight.light, .regular, .semibold] {
            guard let url = Bundle.main.url(forResource: weight.resourceName, withExtension: "ttf") else { continue }
            CTFontManagerRegisterFontsForURL(url as CFURL, .process, nil)
        }
        return UIFont(name: Weight.regular.postScriptName, size: 12) != nil
    }

    /// Resolved once, on first use, so previews and the app behave the same.
    static let interAvailable: Bool = registerFonts()

    /// A missing family must degrade to SF Pro, never render nothing.
    static func font(size: CGFloat, weight: Weight) -> Font {
        interAvailable
            ? .custom(weight.postScriptName, fixedSize: size)
            : .system(size: size, weight: weight.systemFallback)
    }
}

/// One text role: size, face, letter-spacing and line-height, as the markup sets them.
struct TypoStyle {
    let size: CGFloat
    let weight: Typo.Weight
    /// Letter-spacing in em, matching the CSS values (-.02em, +.12em...).
    let trackingEm: CGFloat
    /// CSS line-height multiple, 0 when the design leaves it to the font.
    let lineHeight: CGFloat
    let monospacedDigits: Bool

    init(
        size: CGFloat,
        weight: Typo.Weight,
        trackingEm: CGFloat = 0,
        lineHeight: CGFloat = 0,
        monospacedDigits: Bool = false
    ) {
        self.size = size
        self.weight = weight
        self.trackingEm = trackingEm
        self.lineHeight = lineHeight
        self.monospacedDigits = monospacedDigits
    }

    var font: Font {
        let base = Typo.font(size: size, weight: weight)
        return monospacedDigits ? base.monospacedDigit() : base
    }

    var tracking: CGFloat { size * trackingEm }

    /// SwiftUI's lineSpacing is the gap between lines, not the CSS line box: the
    /// font already carries roughly 1.2x of leading, so only the surplus is added.
    var lineSpacing: CGFloat { lineHeight > 0 ? max(0, size * (lineHeight - 1.2)) : 0 }

    /// Same role, digits locked to a fixed advance.
    var tabular: TypoStyle {
        TypoStyle(
            size: size,
            weight: weight,
            trackingEm: trackingEm,
            lineHeight: lineHeight,
            monospacedDigits: true
        )
    }
}

extension Typo {
    // Headings
    static let wordmark = TypoStyle(size: 22, weight: .semibold, trackingEm: -0.02)
    static let screenTitle = TypoStyle(size: 26, weight: .semibold, trackingEm: -0.02)
    static let articleTitle = TypoStyle(size: 27, weight: .semibold, trackingEm: -0.02, lineHeight: 1.15)
    static let heroTitle = TypoStyle(size: 24, weight: .semibold, trackingEm: -0.02, lineHeight: 1.16)
    static let playerTitle = TypoStyle(size: 23, weight: .semibold, trackingEm: -0.02, lineHeight: 1.18)
    static let sectionTitle = TypoStyle(size: 19, weight: .semibold, trackingEm: -0.01)
    static let chapterTitle = TypoStyle(size: 18, weight: .semibold, trackingEm: -0.01, lineHeight: 1.25)
    static let cardTitle = TypoStyle(size: 16, weight: .semibold, trackingEm: -0.01, lineHeight: 1.25)
    static let statNumber = TypoStyle(size: 22, weight: .semibold, monospacedDigits: true)

    // Labels
    static let overline = TypoStyle(size: 11, weight: .semibold, trackingEm: 0.12)
    static let chip = TypoStyle(size: 10, weight: .semibold, trackingEm: 0.05)
    static let cardTag = TypoStyle(size: 10.5, weight: .semibold, trackingEm: 0.08)
    static let sourcePub = TypoStyle(size: 11, weight: .semibold, trackingEm: 0.06)
    static let dateLabel = TypoStyle(size: 12, weight: .regular, trackingEm: 0.08)
    static let tabLabel = TypoStyle(size: 10, weight: .semibold, trackingEm: 0.04)

    // Rows and body
    static let rowTitleStrong = TypoStyle(size: 14, weight: .semibold)
    static let rowTitle = TypoStyle(size: 14, weight: .regular)
    static let listTitle = TypoStyle(size: 13.5, weight: .regular, lineHeight: 1.35)
    static let paragraph = TypoStyle(size: 15, weight: .light, lineHeight: 1.7)
    static let transcriptBody = TypoStyle(size: 15.5, weight: .light, lineHeight: 1.7)
    static let detail = TypoStyle(size: 12.5, weight: .regular, lineHeight: 1.45)
    static let meta = TypoStyle(size: 12, weight: .regular)
    static let metaSmall = TypoStyle(size: 11.5, weight: .regular)
    static let metaTiny = TypoStyle(size: 11, weight: .regular)

    // Controls
    static let buttonLarge = TypoStyle(size: 14, weight: .semibold)
    static let buttonMedium = TypoStyle(size: 12.5, weight: .semibold)
    static let buttonSmall = TypoStyle(size: 12, weight: .semibold)
    static let pillButton = TypoStyle(size: 11.5, weight: .semibold)
    static let navButton = TypoStyle(size: 13, weight: .semibold)
    static let link = TypoStyle(size: 12.5, weight: .regular)
}

extension View {
    /// Applies a role: face, size, letter-spacing and line-height in one call.
    func typo(_ style: TypoStyle) -> some View {
        self
            .font(style.font)
            .tracking(style.tracking)
            .lineSpacing(style.lineSpacing)
    }
}
